import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import heroImg from '../../public/images/hero.svg'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Quicklance - The first decentralized platform for freelancers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-white dark:bg-gray-900">

        <div className="container px-6 py-16 mx-auto">
          <div className="items-center lg:flex">
            <div className="w-full lg:w-1/2">
              <div className="lg:max-w-lg">
                <h1 className="text-3xl font-semibold text-gray-800 dark:text-white lg:text-4xl">Best Place To Get Started With<br />  <span className="text-blue-500 ">Freelance</span> Quickly!</h1>

                <p className="mt-3 mb-6 text-gray-600 dark:text-gray-400">Find best web3 projects and work on them to get paid securely, find suitable crypto jobs matching your profile, connect easly with other freelancers </p>

                <Link href="/projects" className="w-full px-5 py-2 mt-6 text-sm tracking-wider text-white uppercase font-bold transition-colors duration-300 transform bg-blue-600 rounded-lg lg:w-auto hover:bg-blue-500 focus:outline-none focus:bg-blue-500">Get started</Link>
                <Link href="/freelancers" className="w-full px-5 py-2 mt-6 ml-4 text-sm tracking-wider text-blue-600 font-bold uppercase transition-colors duration-300 transform bg-white rounded-lg lg:w-auto hover:bg-gray-200 focus:outline-none">Hire A Talent</Link>
              </div>
            </div>

            <div className="flex items-center justify-center w-full mt-6 lg:mt-0 lg:w-1/2">
              <Image className="w-full h-full lg:max-w-3xl" src={heroImg} height={60} width={100} alt="Catalogue-pana.svg" />
            </div>
          </div>
        </div>
      </header >
    </>
  )
}
